### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by valeriob** [pruiz/WkHtmlToXSharp#55]
Hi,
running the library on linux it does not seems to have the wkhtmltox0 library embedded, since it produces the following error : 

     An unhandled exception has occurred while executing the request.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unabl                                                    to load shared library 'wkhtmltox0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG env                                                   ronment variable: libwkhtmltox0: cannot open shared object file: No such file or directory
   at WkHtmlToXSharp.NativeCalls.wkhtmltopdf_version()
   at WkHtmlToXSharp.WkHtmlToPdfConverter..ctor()
   at WkHtmlToXSharp.MultiplexingConverter.<>c.<.ctor>b__26_0()
   --- End of inner exception stack trace ---
   at Sanford.Threading.DelegateQueue.EndInvoke(IAsyncResult result)
   at Sanford.Threading.DelegateQueue.Invoke(Delegate method, Object[] args)
   at WkHtmlToXSharp.MultiplexingConverter..ctor()
   at HtmlToPdfCore.Web.Controllers.HomeController.GenerateTestPdf() in C:\Dev\OnitGit\OnTms\src\HtmlToPdf\HtmlToPdfCore.Web\Controllers\HomeC                                                   ntroller.cs:line 26
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExec                                                   tor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

the nuget packages for WkHtmlToXSharp.Linux32 version 1.2.* are all very small (20k) i doubt it has the linux lib embedded, 1.1.latest it's 15+Mb instead, looks working.

Unfortunatly version 1.1.23.22 does not work on windows either :(

Can you point me to a solution ?
Valerio

**Comment by pruiz** [comment]
fetch a wkhtmltox0.so for your linux distro from wkhtmltopdf website, and
copy it to the same folder where you are running your mono app, and try
again.

Regards

**Comment by valeriob** [comment]
Thanks, I have tried that with the same result. I'm running on Ubuntu server.

**Comment by pruiz** [comment]
ensure you have all wkhtmltox0.so dependencies by running ldd against it.
